### ISSUE TITLE
Symfony 3 + only config

### ISSUE THREAD

**Issue by ArmandArthur** [ibrows/IbrowsSonataTranslationBundle#16]
Hello, i use symfony3 and i try to do the tutorial : 
https://github.com/ibrows/IbrowsSonataTranslationBundle/blob/master/README.md

But i have an error : 

```
(1/1) ContextErrorException
Warning: Illegal offset type in isset or empty

C:\wamp64\www\master\vendor\symfony\symfony\src\Symfony\Component\DependencyInjection\ContainerBuilder.php:356
Stack trace:
#0 C:\wamp64\www\master\vendor\symfony\symfony\src\Symfony\Component\DependencyInjection\Compiler\AutowirePass.php(397): Symfony\Component\DependencyInjection\ContainerBuilder->getReflectionClass(Object(Symfony\Component\DependencyInjection\Parameter), false)
#1 C:\wamp64\www\master\vendor\symfony\symfony\src\Symfony\Component\DependencyInjection\Compiler\AutowirePass.php(374): Symfony\Component\DependencyInjection\Compiler\AutowirePass->populateAvailableType('lexik_translati...', Object(Symfony\Component\DependencyInjection\Definition))
#2 C:\wamp64\www\master\vendor\symfony\symfony\src\Symfony\Component\DependencyInjection\Compiler\AutowirePass.php(335): Symfony\Component\DependencyInjection\Compiler\AutowirePass->populateAvailableTypes()
#3 C:\wamp64\www\master\vendor\sy in C:\wamp64\www\master\vendor\symfony\symfony\src\Symfony\Component\DependencyInjection\ContainerBuilder.php on line 356
```
So, it is compatible with symfony 3.3.*?

**Comment by ArmandArthur** [comment]
https://github.com/lexik/LexikTranslationBundle/issues/264
